changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
    authors:
      - github-actions[bot]
      - oc-rsync-bot
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Performance
      labels:
        - performance
    - title: Bug Fixes
      labels:
        - bug
    - title: CI/CD
      labels:
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
