[toolchain]
channel = "1.87.0"
profile = "minimal"
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "llvm-tools-preview",
]
targets = [
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-gnu",
    "i686-pc-windows-gnu",
]
