use std::ffi::OsString;
use std::path::PathBuf;

use core::client::{AddressMode, DeleteMode, HumanReadableMode, StrongChecksumChoice};

use super::bandwidth::BandwidthArgument;
use super::program_name::ProgramName;
use crate::frontend::progress::{NameOutputLevel, ProgressSetting};

/// Parsed command-line arguments for the rsync frontend.
///
/// This structure holds all recognized command-line options after parsing.
/// All fields are `pub` to allow integration tests to inspect arguments.
///
/// **Warning**: This type is exposed via `cli::test_utils` for integration
/// tests only. It is not part of the stable public API.
#[allow(clippy::struct_excessive_bools)]
#[allow(missing_docs)] // Fields are self-documenting; struct is test-only
#[allow(private_interfaces)] // ProgramName, BandwidthArgument are pub(crate) but exposed for tests
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ParsedArgs {
    /// Program name detected from argv\[0\].
    pub program_name: ProgramName,
    pub show_help: bool,
    pub show_version: bool,
    pub human_readable: Option<HumanReadableMode>,
    pub dry_run: bool,
    pub list_only: bool,
    pub remote_shell: Option<OsString>,
    pub connect_program: Option<OsString>,
    pub remote_options: Vec<OsString>,
    pub rsync_path: Option<OsString>,
    pub protect_args: Option<bool>,
    pub old_args: Option<bool>,
    pub address_mode: AddressMode,
    pub bind_address: Option<OsString>,
    pub sockopts: Option<OsString>,
    pub blocking_io: Option<bool>,
    pub archive: bool,
    pub recursive: bool,
    pub recursive_override: Option<bool>,
    pub inc_recursive: Option<bool>,
    pub dirs: Option<bool>,
    pub delete_mode: DeleteMode,
    pub delete_excluded: bool,
    pub delete_missing_args: bool,
    pub ignore_errors: Option<bool>,
    pub backup: bool,
    pub backup_dir: Option<OsString>,
    pub backup_suffix: Option<OsString>,
    pub checksum: Option<bool>,
    pub checksum_choice: Option<StrongChecksumChoice>,
    pub checksum_choice_arg: Option<OsString>,
    pub checksum_seed: Option<u32>,
    pub size_only: bool,
    pub ignore_times: bool,
    pub ignore_existing: bool,
    pub existing: bool,
    pub ignore_missing_args: bool,
    pub update: bool,
    pub remainder: Vec<OsString>,
    pub bwlimit: Option<BandwidthArgument>,
    pub max_delete: Option<OsString>,
    pub min_size: Option<OsString>,
    pub max_size: Option<OsString>,
    pub block_size: Option<OsString>,
    pub modify_window: Option<OsString>,
    pub compress: bool,
    pub no_compress: bool,
    pub compress_level: Option<OsString>,
    pub compress_choice: Option<OsString>,
    pub old_compress: bool,
    pub new_compress: bool,
    pub skip_compress: Option<OsString>,
    pub open_noatime: bool,
    pub no_open_noatime: bool,
    pub iconv: Option<OsString>,
    pub owner: Option<bool>,
    pub group: Option<bool>,
    pub chown: Option<OsString>,
    pub copy_as: Option<OsString>,
    pub usermap: Option<OsString>,
    pub groupmap: Option<OsString>,
    pub chmod: Vec<OsString>,
    pub perms: Option<bool>,
    pub super_mode: Option<bool>,
    pub fake_super: Option<bool>,
    pub times: Option<bool>,
    pub omit_dir_times: Option<bool>,
    pub omit_link_times: Option<bool>,
    pub atimes: Option<bool>,
    pub crtimes: Option<bool>,
    pub acls: Option<bool>,
    pub numeric_ids: Option<bool>,
    pub hard_links: Option<bool>,
    pub links: Option<bool>,
    pub sparse: Option<bool>,
    pub fuzzy: Option<bool>,
    pub copy_links: Option<bool>,
    pub copy_dirlinks: bool,
    pub copy_unsafe_links: Option<bool>,
    pub keep_dirlinks: Option<bool>,
    pub safe_links: bool,
    pub munge_links: Option<bool>,
    pub trust_sender: bool,
    pub server_mode: bool,
    pub write_devices: Option<bool>,
    pub devices: Option<bool>,
    pub copy_devices: bool,
    pub specials: Option<bool>,
    pub force: Option<bool>,
    pub qsort: bool,
    pub relative: Option<bool>,
    pub one_file_system: Option<bool>,
    pub implied_dirs: Option<bool>,
    pub mkpath: bool,
    pub prune_empty_dirs: Option<bool>,
    pub verbosity: u8,
    pub progress: ProgressSetting,
    pub name_level: NameOutputLevel,
    pub name_overridden: bool,
    pub stats: bool,
    pub eight_bit_output: bool,
    pub partial: bool,
    pub preallocate: bool,
    pub fsync: Option<bool>,
    pub delay_updates: bool,
    pub partial_dir: Option<PathBuf>,
    pub temp_dir: Option<PathBuf>,
    pub log_file: Option<OsString>,
    pub log_file_format: Option<OsString>,
    pub write_batch: Option<OsString>,
    pub only_write_batch: Option<OsString>,
    pub read_batch: Option<OsString>,
    pub early_input: Option<OsString>,
    pub link_dests: Vec<PathBuf>,
    pub remove_source_files: bool,
    pub inplace: Option<bool>,
    pub append: Option<bool>,
    pub append_verify: bool,
    pub msgs_to_stderr: Option<bool>,
    pub stderr_mode: Option<OsString>,
    pub outbuf: Option<OsString>,
    pub max_alloc: Option<OsString>,
    pub itemize_changes: bool,
    pub whole_file: Option<bool>,
    pub excludes: Vec<OsString>,
    pub includes: Vec<OsString>,
    pub compare_destinations: Vec<OsString>,
    pub copy_destinations: Vec<OsString>,
    pub link_destinations: Vec<OsString>,
    pub exclude_from: Vec<OsString>,
    pub include_from: Vec<OsString>,
    pub filters: Vec<OsString>,
    pub cvs_exclude: bool,
    pub rsync_filter_shortcuts: usize,
    pub files_from: Vec<OsString>,
    pub from0: bool,
    pub info: Vec<OsString>,
    pub debug: Vec<OsString>,
    pub xattrs: Option<bool>,
    pub no_motd: bool,
    pub password_file: Option<OsString>,
    pub protocol: Option<OsString>,
    pub timeout: Option<OsString>,
    pub contimeout: Option<OsString>,
    pub stop_after: Option<OsString>,
    pub stop_at: Option<OsString>,
    pub out_format: Option<OsString>,
    pub daemon_port: Option<u16>,
    pub dparam: Vec<OsString>,
    pub no_iconv: bool,
    pub executability: Option<bool>,
}
