[package]
name = "rsync-bin"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Rust implementation of the rsync client and daemon binaries"

[[bin]]
name = "rsync"
path = "src/main.rs"

[dependencies]
rsync-cli = { path = "../../crates/cli" }

[package.metadata.deb]
name = "rsync"
section = "utils"
priority = "optional"
maintainer = "Ofer Chen <skewers.irises.3b@icloud.com>"
depends = "libc6 (>= 2.34), libgcc-s1"
extended-description = "Pure-Rust implementation of rsync-compatible client and daemon binaries."
assets = [
    ["../../target/release/rsync", "/usr/bin/rsync", "755"],
    ["../../target/release/rsyncd", "/usr/bin/rsyncd", "755"],
    ["../../packaging/systemd/rsyncd.service", "/lib/systemd/system/rsyncd.service", "644"],
    ["../../packaging/etc/oc-rsyncd/oc-rsyncd.conf", "/etc/oc-rsyncd/oc-rsyncd.conf", "644"],
    ["../../packaging/default/oc-rsyncd", "/etc/default/oc-rsyncd", "644"],
]
conf-files = ["etc/oc-rsyncd/oc-rsyncd.conf", "etc/default/oc-rsyncd"]

[package.metadata.rpm]
package = "rsync"
summary = "Rust implementation of rsync-compatible client and daemon"
requires = ["glibc", "libgcc"]
assets = [
    { path = "../../target/release/rsync", dest = "/usr/bin/rsync", mode = "0755" },
    { path = "../../target/release/rsyncd", dest = "/usr/bin/rsyncd", mode = "0755" },
    { path = "../../packaging/systemd/rsyncd.service", dest = "/usr/lib/systemd/system/rsyncd.service", mode = "0644" },
    { path = "../../packaging/etc/oc-rsyncd/oc-rsyncd.conf", dest = "/etc/oc-rsyncd/oc-rsyncd.conf", mode = "0644", config = true },
    { path = "../../packaging/default/oc-rsyncd", dest = "/etc/default/oc-rsyncd", mode = "0644", config = true },
]
