[package]
name = "rsyncd-bin"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "rsyncd"
path = "src/main.rs"

[features]
default = []
sd-notify = ["rsync-daemon/sd-notify"]

[dependencies]
rsync-daemon = { path = "../../crates/daemon" }
