# Makefile
# Simple targets to wire the scripts

.PHONY: interop server client

interop:
	./scripts/rsync-interop-orchestrator.sh

server:
	./scripts/rsync-interop-server.sh

client:
	./scripts/rsync-interop-client.sh

