#!/usr/bin/env bash
# rsync-interop-client.sh
# ---------------------------------------------------------------------------
# WHAT WAS DONE / WHY:
# - Reads descriptors generated by server.
# - Executes both directions for every version.
# - Validates file existence after transfer.
# - Aggregates failures for CI.
# ---------------------------------------------------------------------------
set -euo pipefail

workspace_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
readonly workspace_root

run_root="${workspace_root}/target/interop/run"
target_dir="${workspace_root}/target/dist"
readonly run_root target_dir

if [[ ! -d "${run_root}" ]]; then
  printf 'run directory %s not found; start rsync-interop-server.sh first\n' "${run_root}" >&2
  exit 1
fi

oc_client="${target_dir}/oc-rsync"
if [[ ! -x "${oc_client}" ]]; then
  printf 'oc-rsync binary not found in %s\n' "${target_dir}" >&2
  exit 1
fi

src="${run_root}/source"
mkdir -p "${src}"
printf 'interop-test\n' > "${src}/payload.txt"

declare -a failed=()

for envfile in "${run_root}"/*/env; do
  if [[ ! -f "${envfile}" ]]; then
    continue
  fi
  # shellcheck disable=SC1090
  source "${envfile}"

  if [[ ! -x "${UPSTREAM_BIN}" ]]; then
    printf 'Upstream binary %s is missing for %s\n' "${UPSTREAM_BIN}" "${VERSION}" >&2
    failed+=("${VERSION} (missing upstream)")
    continue
  fi

  printf 'Testing upstream rsync %s client -> oc-rsync daemon (port %s)\n' "${VERSION}" "${OC_PORT}"
  if ! "${UPSTREAM_BIN}" -av --timeout=10 "${src}/" "rsync://127.0.0.1:${OC_PORT}/interop" >/dev/null 2>&1; then
    printf 'FAIL: upstream %s -> oc-rsync daemon\n' "${VERSION}" >&2
    printf '--- oc log ---\n' >&2
    cat "${OC_LOG}" >&2 || true
    failed+=("${VERSION} (upstream->oc)")
  else
    if [[ ! -f "${OC_DEST}/payload.txt" ]]; then
      printf 'FAIL: upstream %s reported success but file missing in oc dest\n' "${VERSION}" >&2
      failed+=("${VERSION} (missing in oc dest)")
    fi
  fi

  printf 'Testing oc-rsync client -> upstream rsync %s daemon (port %s)\n' "${VERSION}" "${UPSTREAM_PORT}"
  if ! "${OC_BIN}" -av --timeout=10 "${src}/" "rsync://127.0.0.1:${UPSTREAM_PORT}/interop" >/dev/null 2>&1; then
    printf 'FAIL: oc-rsync client -> upstream %s daemon\n' "${VERSION}" >&2
    printf '--- upstream log ---\n' >&2
    cat "${UP_LOG}" >&2 || true
    failed+=("${VERSION} (oc->up)")
  else
    if [[ ! -f "${UP_DEST}/payload.txt" ]]; then
      printf 'FAIL: oc-rsync -> upstream %s daemon: file missing\n' "${VERSION}" >&2
      failed+=("${VERSION} (missing in upstream dest)")
    fi
  fi
done

if (( ${#failed[@]} > 0 )); then
  printf 'Interop failures: %s\n' "${failed[*]}" >&2
  exit 1
fi

printf 'All interoperability checks succeeded.\n'

